# fly.toml app configuration file generated for your-rasa-bot on 2025-08-11T13:17:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "your-rasa-bot"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5005"
  # Set these in Fly.io dashboard or using `fly secrets set`
  # SUPABASE_URL = ""
  # SUPABASE_KEY = ""
  # SUPABASE_DB_URL = ""

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  http_checks = []
  internal_port = 5005
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"